[package]
name = "hideit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hideit!"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
